### ISSUE TITLE
Tags: Page could not be found on images including / in their name

### ISSUE THREAD

**Issue by ArGJolan** [Tchoupinax/fuzzy-engine#11]
The show tags page displays "This page could not be found" for image containing a `/`

How to reproduce:
- Have an image name containing / (e.g: `registry.example.com/my/image`)
- Show images of your registry
- Click on `Show tags`
- Error page shows

![image](https://user-images.githubusercontent.com/11016546/111809545-62af4f80-88d5-11eb-846d-b12c72fe7dae.png)

**Comment by Tchoupinax** [comment]
Hello @ArGJolan,

Thank you for your report.
The version [1.0.10](https://github.com/Tchoupinax/fuzzy-engine/releases/tag/v1.0.10) should solve your issue.

Please try it and close the issue if the problem has disappeared. :)

**Comment by ArGJolan** [comment]
Fixed, thanks 🥇
