### ISSUE TITLE
can't run in centos 7

### ISSUE THREAD

**Issue by wowtrxqn** [Tchoupinax/fuzzy-engine#25]
![ui](https://user-images.githubusercontent.com/24369118/178396122-742347b8-472a-4af5-b5f1-3b429fad8676.jpeg)

**Comment by Tchoupinax** [comment]
Hello @wowtrxqn,

Thank you for reporting. Can you please give me which command did you use ?
This following one? 

```
docker run -d -p 3000:3000 tchoupinax/fuzzy-engine
```

Also, can you provide me information about your OS please for reproducing ? (`centos 7`)

```
uname -a
```

**Comment by wowtrxqn** [comment]
> Hello @wowtrxqn,
> 
> Thank you for reporting. Can you please give me which command did you use ? This following one?
> 
> ```
> docker run -d -p 3000:3000 tchoupinax/fuzzy-engine
> ```
> 
> Also, can you provide me information about your OS please for reproducing ? (`centos 7`)
> 
> ```
> uname -a
> ```

![368](https://user-images.githubusercontent.com/24369118/179476890-8de02629-fbb3-4ded-89c1-50286cca31a6.jpeg)

**Comment by wowtrxqn** [comment]
when use latest image version , still has error: 
![latest](https://user-images.githubusercontent.com/24369118/179479567-4eeb6b55-a147-4625-8aa1-a23b70d5faf3.jpeg)

**Comment by Tchoupinax** [comment]
I made changes in the Dockerfile, can you try again with the latest image please ? (tag: `latest`).

**Comment by Tchoupinax** [comment]
I think this release fixes you issue now I correctly understand the issue.

https://github.com/Tchoupinax/fuzzy-engine/releases/tag/v1.4.1

Please free to open again if the issue persists. :)

**Comment by wowtrxqn** [comment]
> I think this release fixes you issue now I correctly understand the issue.
> 
> https://github.com/Tchoupinax/fuzzy-engine/releases/tag/v1.4.1
> 
> Please free to open again if the issue persists. :)

ok, thanks , but my registry don't have username and password , the 'show docker images' button status is disables unless input username & password

**Comment by Tchoupinax** [comment]
I'm not sure how to do it, can you share how you declared you registry to not have username and password?
