### ISSUE TITLE
Can't connect to docker registry without username/password

### ISSUE THREAD

**Issue by Tchoupinax** [Tchoupinax/fuzzy-engine#28]
As @wowtrxqn mentionned here, we are not able to connect to a passwordless registry https://github.com/Tchoupinax/fuzzy-engine/issues/25#issuecomment-1191472624.

**Comment by wowtrxqn** [comment]
just simple command run "docker run -d -p 5001:5000 --name registry-srv registry:2", i want to connect this registry but can't find username/password

**Comment by Tchoupinax** [comment]
I see. The new tag [v1.4.2](https://github.com/Tchoupinax/fuzzy-engine/releases/tag/v1.4.2) allows it.
Enjoy! :)
