### ISSUE TITLE
403 error with traefik

### ISSUE THREAD

**Issue by MathieuGery** [Tchoupinax/fuzzy-engine#4]
I setup fuzzy to use traefik as reverse proxy but i have an error.

Forbidden
You don't have permission to access / on this server.

Someone can help me ?
Have a good day

**Comment by Tchoupinax** [comment]
Hello,

Thank you for your report. I find it strange because this [demo](https://fuzzy-engine.corentinfiloche.xyz/) is hosted behind Traefik ^^.

What is your Traefik version ?
Thanks, have a good day too

**Comment by Tchoupinax** [comment]
Be free to reopen it if you are interested again :)
